Normalize line endings in SSH key for the underlying OS
easingthemes/ssh-deploy pull request #156
Opened 2023-07-26 10:37 UTC by mansandersson

This fixes issue #143 on my side

This is my first ever nodejs commit so please help me out if I've done something completely unacceptable.

2023-09-24 15:03 UTC, easingthemes requested changes

2023-09-24 15:03 UTC, easingthemes commented on package.json
> +    "os": "^0.1.2",
`os` is native nodeJS module, please remove it as a dependency

2023-09-24 15:03 UTC, easingthemes commented on src/sshKey.js
> +const { EOL } = require('os');
Move line up in a group with other nodeJS modules

2023-09-24 15:03 UTC, easingthemes commented on package-lock.json
After removing dependencies there should be no changes to package.lock.

2023-09-24 15:24 UTC, codespearhead commented
@mansandersson are you still willing to act on the changes and have this PR merged?

2023-09-24 16:54 UTC, mansandersson commented
> @mansandersson are you still willing to act on the changes and have this PR merged?

Yes, I'm willing to make the changes required

2023-09-24 19:18 UTC, codespearhead commented
> > @mansandersson are you still willing to act on the changes and have this PR merged?
> 
> Yes, I'm willing to make the changes required

Understood. Let me know if you need help! 😄

2023-09-25 20:04 UTC, easingthemes commented
Thanks.
Just one more: resolve conflicts in dist. Remove `dist/index.js` and rebuild it locally, then push new version.
Pleas use `fix: some message` in commit message so that release can be automatically triggered.

2023-09-28 18:05 UTC, mansandersson commented
> Thanks. Just one more: resolve conflicts in dist. Remove `dist/index.js` and rebuild it locally, then push new version. Pleas use `fix: some message` in commit message so that release can be automatically triggered.

Done. Let me know if anything else needs fixing.

2023-09-30 15:06 UTC, joebnb commented
waiting for merging

2023-09-30 15:12 UTC, easingthemes approved these changes

2023-09-30 15:12 UTC, merged

2023-09-30 15:13 UTC, easingthemes commented
Thanks